version: "3"

services:
  relay:
    image: scsibug/nostr-rs-relay:0.8.13
    ports:
      - 7000:8080
    volumes:
      - ./data:/usr/src/app/db
  dvm:
    build: .
    restart: unless-stopped
    depends_on:
      - relay
    environment:
      SQLITE_DB: /data
    volumes:
      - ./data:/data
